apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    {{- include "p2.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    {{- include "p2.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.web.port }}
      targetPort: http
