apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
