apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    {{- include "p2.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      {{- include "p2.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "p2.labels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: {{ include "p2.image" (dict "image" .Values.web.image "root" .) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.port }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
