"""Review -> Product aggregation pipeline (Step 2).

Pure aggregation logic (``aggregate_products``) is deliberately separated from
file I/O (``load_reviews`` / ``run``) so it is unit-testable without fixtures on
disk. Run as a module to (re)generate the catalog + data report:

    uv run python -m core.aggregate
"""

from __future__ import annotations

import csv
import json
import statistics
from pathlib import Path

from core.models import Product, Review

DEFAULT_CSV = Path("demo/data/flipkart_product_review.csv")
DEFAULT_PRODUCTS_OUT = Path("data/products.json")
DEFAULT_REPORT_OUT = Path("docs/data-report.md")
REPRESENTATIVE_REVIEWS = 8


def load_reviews(csv_path: Path) -> tuple[list[Review], list[str]]:
    """Load and validate reviews from CSV. Returns (valid_reviews, error_messages)."""
    reviews: list[Review] = []
    errors: list[str] = []
    with csv_path.open(encoding="utf-8", newline="") as f:
        for i, row in enumerate(csv.DictReader(f), start=2):  # row 1 is the header
            try:
                reviews.append(Review.model_validate(row))
            except Exception as exc:  # collect bad rows, don't crash the batch
                errors.append(f"row {i}: {exc}")
    return reviews, errors


def _representative_reviews(texts: list[str], n: int) -> list[str]:
    """Deterministically pick the n most informative (longest, de-duplicated) reviews."""
    seen: set[str] = set()
    unique: list[str] = []
    for text in sorted(texts, key=len, reverse=True):
        cleaned = text.strip()
        key = cleaned.lower()
        if key and key not in seen:
            seen.add(key)
            unique.append(cleaned)
    return unique[:n]


def aggregate_products(
    reviews: list[Review], n_representative: int = REPRESENTATIVE_REVIEWS
) -> list[Product]:
    """Group reviews by product_id and compute product-level recommender features."""
    by_id: dict[str, list[Review]] = {}
    for review in reviews:
        by_id.setdefault(review.product_id, []).append(review)

    products: list[Product] = []
    for product_id, group in sorted(by_id.items()):
        ratings = [r.rating for r in group]
        histogram = {star: 0 for star in range(1, 6)}
        for star in ratings:
            histogram[star] += 1
        representative = _representative_reviews([r.review for r in group], n_representative)
        summaries = sorted({r.summary.strip() for r in group if r.summary.strip()})
        title = group[0].product_title
        combined_text = title + "\n" + "\n".join(representative)
        products.append(
            Product(
                product_id=product_id,
                title=title,
                review_count=len(group),
                avg_rating=round(statistics.fmean(ratings), 3),
                rating_histogram=histogram,
                representative_reviews=representative,
                summary_phrases=summaries,
                combined_text=combined_text,
            )
        )
    return products


def build_data_report(reviews: list[Review], products: list[Product], errors: list[str]) -> str:
    """Render a markdown data-quality report so we *see* the data before embedding."""
    overall_hist = {star: 0 for star in range(1, 6)}
    for review in reviews:
        overall_hist[review.rating] += 1
    n_reviews = len(reviews)

    lines: list[str] = [
        "# Data Quality Report — Flipkart product reviews",
        "",
        "> Generated by `core.aggregate` (Step 2). "
        "Source: `demo/data/flipkart_product_review.csv`.",
        "",
        "## Totals",
        "",
        f"- Review rows (valid): **{n_reviews}**",
        f"- Distinct products: **{len(products)}**",
        f"- Validation errors: **{len(errors)}**",
        "",
        "## Per-product summary",
        "",
        "| product_id | title | reviews | avg_rating | 1★ | 2★ | 3★ | 4★ | 5★ |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for p in products:
        h = p.rating_histogram
        lines.append(
            f"| {p.product_id} | {p.title} | {p.review_count} | {p.avg_rating:.2f} "
            f"| {h[1]} | {h[2]} | {h[3]} | {h[4]} | {h[5]} |"
        )

    lines += [
        "",
        "## Overall rating distribution",
        "",
        "| rating | count | share |",
        "|---|---|---|",
    ]
    for star in range(1, 6):
        share = (overall_hist[star] / n_reviews * 100) if n_reviews else 0.0
        lines.append(f"| {star}★ | {overall_hist[star]} | {share:.1f}% |")

    lines += [
        "",
        "## ⚠️ Scope caveat (honest read of the data)",
        "",
        "- The catalog is **only 9 products, all in one category (audio: "
        "headsets / earbuds / neckbands)**. This is *within-category* recommendation "
        "(pick the best audio product for a stated need: bass / battery / calls / "
        "budget), **not** a broad multi-category recommender.",
        "- Ratings are heavily skewed to 4–5★, so `avg_rating` discriminates weakly; "
        "the ranking signal will lean more on semantic relevance + review evidence than "
        "on rating alone.",
        "- Implication for the **Step 5 ranking-eval gate**: with 9 products, use small "
        "`k` (e.g. k=3) and weight **NDCG/MRR (ordering quality)** over Recall@k "
        "(near-trivial at this catalog size). We decide go/no-go on those numbers.",
    ]
    if errors:
        lines += ["", "## Validation errors", "", *[f"- {e}" for e in errors]]
    return "\n".join(lines) + "\n"


def run(
    csv_path: Path = DEFAULT_CSV,
    products_out: Path = DEFAULT_PRODUCTS_OUT,
    report_out: Path = DEFAULT_REPORT_OUT,
) -> list[Product]:
    """Load -> aggregate -> write catalog JSON + data report. Returns the products."""
    reviews, errors = load_reviews(csv_path)
    products = aggregate_products(reviews)

    products_out.parent.mkdir(parents=True, exist_ok=True)
    products_out.write_text(
        json.dumps([p.model_dump() for p in products], indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    report_out.parent.mkdir(parents=True, exist_ok=True)
    report_out.write_text(build_data_report(reviews, products, errors), encoding="utf-8")

    print(f"reviews={len(reviews)} products={len(products)} errors={len(errors)}")
    print(f"wrote {products_out}")
    print(f"wrote {report_out}")
    return products


if __name__ == "__main__":
    run()
