import { LegalPage } from "@/components/LegalPage";

export const metadata = { title: "Terms of Service — ProductIQ" };

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      updated="June 1, 2026"
      intro="These terms govern your use of ProductIQ. By creating an account or using the service, you agree to them."
      sections={[
        {
          heading: "Acceptance of terms",
          body: [
            "By accessing or using ProductIQ, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree, do not use the service.",
          ],
        },
        {
          heading: "The service",
          body: [
            "ProductIQ provides AI-powered product discovery: semantic search, rating-aware ranking, and generated explanations grounded in product reviews.",
            "Recommendations are generated by AI and provided for informational purposes. We do not guarantee that any recommended product is suitable for your particular needs — always use your own judgment before purchasing.",
          ],
        },
        {
          heading: "Accounts and plans",
          body: [
            "You are responsible for maintaining the confidentiality of your account. The Free plan includes a daily search quota; paid plans (Pro, Enterprise) unlock higher limits and additional features.",
            "You may upgrade, downgrade, or cancel at any time. Fees for paid plans are billed in advance and are non-refundable except as described in our refund policy.",
          ],
        },
        {
          heading: "Acceptable use",
          body: [
            "You agree not to abuse the service, including attempting to bypass rate limits or quotas, scraping at scale, reverse-engineering the ranking system, or using the service for any unlawful purpose.",
            "We reserve the right to suspend accounts that violate these terms or place undue load on the platform.",
          ],
        },
        {
          heading: "Intellectual property",
          body: [
            "ProductIQ and its underlying technology, design, and content are our property. Product data and reviews belong to their respective owners and are used to power discovery.",
          ],
        },
        {
          heading: "Disclaimers and liability",
          body: [
            "The service is provided 'as is' without warranties of any kind. To the maximum extent permitted by law, we are not liable for any indirect, incidental, or consequential damages arising from your use of the service.",
          ],
        },
        {
          heading: "Changes to these terms",
          body: [
            "We may update these terms from time to time. Material changes will be communicated via email or an in-app notice. Continued use after changes constitutes acceptance.",
          ],
        },
        {
          heading: "Contact",
          body: ["Questions about these terms? Email legal@productiq.app."],
        },
      ]}
    />
  );
}
